package lejos.ev3.c;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : lms2012.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class MOTORDATA extends Structure {
	/** C type : SLONG */
	public int TachoCounts;
	public int getTachoCounts() {
		return TachoCounts;
	}
	public void setTachoCounts(int TachoCounts) {
		this.TachoCounts = TachoCounts;
	}
	/** C type : SBYTE */
	public byte Speed;
	public byte getSpeed() {
		return Speed;
	}
	public void setSpeed(byte Speed) {
		this.Speed = Speed;
	}
	/** C type : SLONG */
	public int TachoSensor;
	public int getTachoSensor() {
		return TachoSensor;
	}
	public void setTachoSensor(int TachoSensor) {
		this.TachoSensor = TachoSensor;
	}
	public MOTORDATA() {
		super();
	}
	public MOTORDATA(Pointer peer) {
		super(peer);
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("TachoCounts", "Speed", "TachoSensor");
	}
	/**
	 * @param TachoCounts C type : SLONG<br>
	 * @param Speed C type : SBYTE<br>
	 * @param TachoSensor C type : SLONG
	 */
	public MOTORDATA(int TachoCounts, byte Speed, int TachoSensor) {
		super();
		this.TachoCounts = TachoCounts;
		this.Speed = Speed;
		this.TachoSensor = TachoSensor;
	}
	public static class ByReference extends MOTORDATA implements Structure.ByReference {
		
	};
	public static class ByValue extends MOTORDATA implements Structure.ByValue {
		
	};
}
