package lejos.ev3.c;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : lms2012.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NONVOL extends Structure {
	/**
	 * !< System default volume [0..100%]<br>
	 * C type : DATA8
	 */
	public byte VolumePercent;
	public byte getVolumePercent() {
		return VolumePercent;
	}
	public void setVolumePercent(byte VolumePercent) {
		this.VolumePercent = VolumePercent;
	}
	/**
	 * !< System sleep          [0..120min] (0 = ~)<br>
	 * C type : DATA8
	 */
	public byte SleepMinutes;
	public byte getSleepMinutes() {
		return SleepMinutes;
	}
	public void setSleepMinutes(byte SleepMinutes) {
		this.SleepMinutes = SleepMinutes;
	}
	public NONVOL() {
		super();
	}
	public NONVOL(Pointer address) {
		super(address);
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("VolumePercent", "SleepMinutes");
	}
	/**
	 * @param VolumePercent !< System default volume [0..100%]<br>
	 * C type : DATA8<br>
	 * @param SleepMinutes !< System sleep          [0..120min] (0 = ~)<br>
	 * C type : DATA8
	 */
	public NONVOL(byte VolumePercent, byte SleepMinutes) {
		super();
		this.VolumePercent = VolumePercent;
		this.SleepMinutes = SleepMinutes;
	}
	public static class ByReference extends NONVOL implements Structure.ByReference {
		
	};
	public static class ByValue extends NONVOL implements Structure.ByValue {
		
	};
}
