package lejos.ev3.c;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : lms2012.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class STEPPOWER extends Structure {
	/** C type : DATA8 */
	public byte Cmd;
	public byte getCmd() {
		return Cmd;
	}
	public void setCmd(byte Cmd) {
		this.Cmd = Cmd;
	}
	/** C type : DATA8 */
	public byte Nos;
	public byte getNos() {
		return Nos;
	}
	public void setNos(byte Nos) {
		this.Nos = Nos;
	}
	/** C type : DATA8 */
	public byte Power;
	public byte getPower() {
		return Power;
	}
	public void setPower(byte Power) {
		this.Power = Power;
	}
	/** C type : DATA32 */
	public int Step1;
	public int getStep1() {
		return Step1;
	}
	public void setStep1(int Step1) {
		this.Step1 = Step1;
	}
	/** C type : DATA32 */
	public int Step2;
	public int getStep2() {
		return Step2;
	}
	public void setStep2(int Step2) {
		this.Step2 = Step2;
	}
	/** C type : DATA32 */
	public int Step3;
	public int getStep3() {
		return Step3;
	}
	public void setStep3(int Step3) {
		this.Step3 = Step3;
	}
	/** C type : DATA8 */
	public byte Brake;
	public byte getBrake() {
		return Brake;
	}
	public void setBrake(byte Brake) {
		this.Brake = Brake;
	}
	public STEPPOWER() {
		super();
	}
	public STEPPOWER(Pointer address) {
		super(address);
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("Cmd", "Nos", "Power", "Step1", "Step2", "Step3", "Brake");
	}
	/**
	 * @param Cmd C type : DATA8<br>
	 * @param Nos C type : DATA8<br>
	 * @param Power C type : DATA8<br>
	 * @param Step1 C type : DATA32<br>
	 * @param Step2 C type : DATA32<br>
	 * @param Step3 C type : DATA32<br>
	 * @param Brake C type : DATA8
	 */
	public STEPPOWER(byte Cmd, byte Nos, byte Power, int Step1, int Step2, int Step3, byte Brake) {
		super();
		this.Cmd = Cmd;
		this.Nos = Nos;
		this.Power = Power;
		this.Step1 = Step1;
		this.Step2 = Step2;
		this.Step3 = Step3;
		this.Brake = Brake;
	}
	public static class ByReference extends STEPPOWER implements Structure.ByReference {
		
	};
	public static class ByValue extends STEPPOWER implements Structure.ByValue {
		
	};
}
