package lejos.ev3.c;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : lms2012.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class UI extends Structure {
	/**
	 * !< Pressed status<br>
	 * C type : DATA8[6]
	 */
	public byte[] Pressed = new byte[6];
	public byte[] getPressed() {
		return Pressed;
	}
	public void setPressed(byte Pressed[]) {
		this.Pressed = Pressed;
	}
	public UI() {
		super();
	}
	public UI(Pointer address) {
		super(address);
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("Pressed");
	}
	/**
	 * @param Pressed !< Pressed status<br>
	 * C type : DATA8[6]
	 */
	public UI(byte Pressed[]) {
		super();
		if ((Pressed.length != this.Pressed.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.Pressed = Pressed;
	}
	public static class ByReference extends UI implements Structure.ByReference {
		
	};
	public static class ByValue extends UI implements Structure.ByValue {
		
	};
}
