package lejos.ev3.c;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : lms2012.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class USB_SPEED extends Structure {
	/** C type : DATA8 */
	public byte Speed;
	public byte getSpeed() {
		return Speed;
	}
	public void setSpeed(byte Speed) {
		this.Speed = Speed;
	}
	public USB_SPEED() {
		super();
	}
	public USB_SPEED(Pointer address) {
		super(address);
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("Speed");
	}
	/** @param Speed C type : DATA8 */
	public USB_SPEED(byte Speed) {
		super();
		this.Speed = Speed;
	}
	public static class ByReference extends USB_SPEED implements Structure.ByReference {
		
	};
	public static class ByValue extends USB_SPEED implements Structure.ByValue {
		
	};
}
